### ISSUE TITLE
player can build word by repeating given characters

### ISSUE THREAD

**Issue by nDZIB** [Nelson-J/word_game#4]
Suppose a player is given the characters 'EFI', if the player suggests the word 'fee', it will be accepted and they will get points for the word

**Comment by Nelson-J** [comment]
Have you tried it?
Could you replicate the behaviour and display?

**Comment by nDZIB** [comment]
![issue](https://user-images.githubusercontent.com/48608377/80272399-e09fb200-8696-11ea-9794-3b1e5fe537e0.png)

Specifically the first two player suggestions in the image

**Comment by Nelson-J** [comment]
Solution found: 
Player guess is verified by checking that it is present in the subword list
- Present? the point is awarded
- Not present a 0 point is awarded
